using System.Text.Json;
using Microsoft.Extensions.Logging;
using VRCFaceTracking.Core.Contracts;
using VRCFaceTracking.Core.Models.ParameterDefinition.FileBased;
using VRCFaceTracking.Core.Params;
using VRCFaceTracking.Core.Services;

namespace VRCFaceTracking.Core;

/// <summary>Reads the OSC avatar configuration generated by VRChat.</summary>
public class AvatarConfigParser(ILogger<AvatarConfigParser> parserLogger)
{
    public async Task<(IAvatarInfo avatarInfo, List<Parameter> relevantParameters)?> ParseAvatar(
        string newId, bool skipParams = false)
    {
        var avatarConfig = await ReadAvatarConfigAsync(newId);
        if (avatarConfig == null)
            return null;

        var relevantParameters = new List<Parameter>();
        if (!skipParams)
        {
            parserLogger.LogInformation("Parsing config file for avatar: {avatarName}", avatarConfig.name);
            ParameterSenderService.Clear();
            var inputs = avatarConfig.parameters
                .Where(parameter => parameter.input != null)
                .Cast<IParameterDefinition>()
                .ToArray();

            foreach (var parameter in UnifiedTracking.AllParameters)
                relevantParameters.AddRange(parameter.ResetParam(inputs, avatarConfig));
        }

        return (avatarConfig, relevantParameters);
    }

    public async Task<AvatarConfigFile?> ReadAvatarConfigAsync(string? avatarId)
    {
        if (!IsValidAvatarId(avatarId))
            return null;

        foreach (var avatarsDirectory in EnumerateAvatarDirectories())
        {
            var path = Path.Combine(avatarsDirectory, avatarId + ".json");
            if (!File.Exists(path))
                continue;

            var config = await TryReadConfigAsync(path);
            if (config?.id == avatarId)
                return config;
        }

        return null;
    }

    public async Task<AvatarConfigFile?> ReadMostRecentConfigAsync()
    {
        var paths = new List<string>();
        foreach (var directory in EnumerateAvatarDirectories())
        {
            try
            {
                paths.AddRange(Directory.EnumerateFiles(directory, "avtr_*.json"));
            }
            catch (Exception ex) when (ex is IOException or UnauthorizedAccessException)
            {
                parserLogger.LogWarning(ex, "Could not enumerate avatar configs in {directory}", directory);
            }
        }

        foreach (var path in paths.OrderByDescending(File.GetLastWriteTimeUtc))
        {
            var config = await TryReadConfigAsync(path);
            if (config != null && config.id == Path.GetFileNameWithoutExtension(path)
                && IsValidAvatarId(config.id))
                return config;
        }

        return null;
    }

    private static bool IsValidAvatarId(string? avatarId) =>
        !string.IsNullOrWhiteSpace(avatarId) && avatarId.StartsWith("avtr_", StringComparison.Ordinal)
        && avatarId.All(c => char.IsLetterOrDigit(c) || c is '_' or '-');

    private IEnumerable<string> EnumerateAvatarDirectories()
    {
        var root = VRChat.VRCOSCDirectory;
        if (string.IsNullOrEmpty(root) || !Directory.Exists(root))
            return [];

        try
        {
            return Directory.EnumerateDirectories(root)
                .Select(userDirectory => Path.Combine(userDirectory, "Avatars"))
                .Where(Directory.Exists)
                .ToArray();
        }
        catch (Exception ex) when (ex is IOException or UnauthorizedAccessException)
        {
            parserLogger.LogWarning(ex, "Could not enumerate VRChat OSC directory {root}", root);
            return [];
        }
    }

    private async Task<AvatarConfigFile?> TryReadConfigAsync(string path)
    {
        try
        {
            var config = JsonSerializer.Deserialize<AvatarConfigFile>(await File.ReadAllTextAsync(path));
            return config?.parameters != null ? config : null;
        }
        catch (Exception ex) when (ex is JsonException or IOException or UnauthorizedAccessException)
        {
            parserLogger.LogWarning(ex, "Could not read avatar config {path}", path);
            return null;
        }
    }
}
