//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VRCFaceTracking.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    ///   This class was generated by MSBuild using the GenerateResource task.
    ///   To add or remove a member, edit your .resx file then rerun MSBuild.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Build.Tasks.StronglyTypedResourceBuilder", "15.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VRCFaceTracking.Strings.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About_Text {
            get {
                return ResourceManager.GetString("About_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VRCFaceTracking.
        /// </summary>
        public static string AppDescription {
            get {
                return ResourceManager.GetString("AppDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VRCFaceTracking.
        /// </summary>
        public static string AppDisplayName {
            get {
                return ResourceManager.GetString("AppDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appearance.
        /// </summary>
        public static string Appearance_Text {
            get {
                return ResourceManager.GetString("Appearance_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;toast launch=&quot;action=ToastClick&quot;&gt;
        ///  &lt;visual&gt;
        ///    &lt;binding template=&quot;ToastGeneric&quot;&gt;
        ///      &lt;text&gt;App Notification&lt;/text&gt;
        ///      &lt;text&gt;&lt;/text&gt;
        ///      &lt;image placement=&quot;appLogoOverride&quot; hint-crop=&quot;circle&quot; src=&quot;{0}Assets/WindowIcon.ico&quot;/&gt;
        ///    &lt;/binding&gt;
        ///  &lt;/visual&gt;
        ///  &lt;actions&gt;
        ///    &lt;action content=&quot;Settings&quot; arguments=&quot;action=Settings&quot;/&gt;
        ///  &lt;/actions&gt;
        ///&lt;/toast&gt;.
        /// </summary>
        public static string AppNotificationSamplePayload {
            get {
                return ResourceManager.GetString("AppNotificationSamplePayload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author.
        /// </summary>
        public static string Author_Text {
            get {
                return ResourceManager.GetString("Author_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Start when SteamVR is launched.
        /// </summary>
        public static string AutoStartSettings_Description {
            get {
                return ResourceManager.GetString("AutoStartSettings_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Start.
        /// </summary>
        public static string AutoStartSettings_Header {
            get {
                return ResourceManager.GetString("AutoStartSettings_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avatar Status.
        /// </summary>
        public static string AvatarStatus_Text {
            get {
                return ResourceManager.GetString("AvatarStatus_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File a bug report.
        /// </summary>
        public static string BugRequestCard_Header {
            get {
                return ResourceManager.GetString("BugRequestCard_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calibrate.
        /// </summary>
        public static string CalibrateButton_Content {
            get {
                return ResourceManager.GetString("CalibrateButton_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggles whether or not calibration is enabled.
        /// </summary>
        public static string CalibrationEnabledToggle_Description {
            get {
                return ResourceManager.GetString("CalibrationEnabledToggle_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calibration Enabled.
        /// </summary>
        public static string CalibrationEnabledToggle_Header {
            get {
                return ResourceManager.GetString("CalibrationEnabledToggle_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls how much of an influence your facial expressions have on overall calibration over time.
        /// </summary>
        public static string CalibrationInfluenceSlider_Description {
            get {
                return ResourceManager.GetString("CalibrationInfluenceSlider_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calibration Influence.
        /// </summary>
        public static string CalibrationInfluenceSlider_Header {
            get {
                return ResourceManager.GetString("CalibrationInfluenceSlider_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tweak tracking data to your heart&apos;s content.
        /// </summary>
        public static string CalibrationSettings_Description {
            get {
                return ResourceManager.GetString("CalibrationSettings_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calibration Settings.
        /// </summary>
        public static string CalibrationSettings_Header {
            get {
                return ResourceManager.GetString("CalibrationSettings_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To clone this repository.
        /// </summary>
        public static string CloneRepoCard_Header {
            get {
                return ResourceManager.GetString("CloneRepoCard_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slowly calibrates to your facial expressions over time.
        /// </summary>
        public static string ContCalibrationToggle_Description {
            get {
                return ResourceManager.GetString("ContCalibrationToggle_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continuous Calibration.
        /// </summary>
        public static string ContCalibrationToggle_Header {
            get {
                return ResourceManager.GetString("ContCalibrationToggle_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to © 2023 VRCFaceTracking. All rights reserved..
        /// </summary>
        public static string Copyright_Description {
            get {
                return ResourceManager.GetString("Copyright_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The nerds who made this all possible &lt;3.
        /// </summary>
        public static string Credits_Description {
            get {
                return ResourceManager.GetString("Credits_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dependencies &amp; references.
        /// </summary>
        public static string Dependencies_Header {
            get {
                return ResourceManager.GetString("Dependencies_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description_Text {
            get {
                return ResourceManager.GetString("Description_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to THIS CODE AND INFORMATION IS PROVIDED ‘AS IS’ WITHOUT WARRANTY OF ANY KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF MERCHANTABILITY AND/OR FITNESS FOR A PARTICULAR PURPOSE..
        /// </summary>
        public static string Disclaimer_Header {
            get {
                return ResourceManager.GetString("Disclaimer_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloads.
        /// </summary>
        public static string Downloads_Text {
            get {
                return ResourceManager.GetString("Downloads_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eye Tracking Active.
        /// </summary>
        public static string EyeTrackingActive_Text {
            get {
                return ResourceManager.GetString("EyeTrackingActive_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eye Tracking Inactive.
        /// </summary>
        public static string EyeTrackingInactive_Text {
            get {
                return ResourceManager.GetString("EyeTrackingInactive_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Face Tracking Active.
        /// </summary>
        public static string FaceTrackingActive_Text {
            get {
                return ResourceManager.GetString("FaceTrackingActive_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Face Tracking Inactive.
        /// </summary>
        public static string FaceTrackingInactive_Text {
            get {
                return ResourceManager.GetString("FaceTrackingInactive_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Force VRCFT to unload and reinitialize all modules.
        /// </summary>
        public static string ForceReInitButton_Description {
            get {
                return ResourceManager.GetString("ForceReInitButton_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Force Re-Initialize.
        /// </summary>
        public static string ForceReInitButton_Header {
            get {
                return ResourceManager.GetString("ForceReInitButton_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forces sending of all parameters every frame by forcing relevancy.
        /// </summary>
        public static string ForceRelevancyToggle_Description {
            get {
                return ResourceManager.GetString("ForceRelevancyToggle_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Force Relevancy.
        /// </summary>
        public static string ForceRelevancyToggle_Header {
            get {
                return ResourceManager.GetString("ForceRelevancyToggle_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stare at your tongue I guess?.
        /// </summary>
        public static string HardwareDebug_Description {
            get {
                return ResourceManager.GetString("HardwareDebug_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hardware Debug.
        /// </summary>
        public static string HardwareDebug_Header {
            get {
                return ResourceManager.GetString("HardwareDebug_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Updated.
        /// </summary>
        public static string LastUpdated_Text {
            get {
                return ResourceManager.GetString("LastUpdated_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legacy Parameters.
        /// </summary>
        public static string LegacyParameters_Text {
            get {
                return ResourceManager.GetString("LegacyParameters_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select an item from the list..
        /// </summary>
        public static string ListDetails_NoSelection_Text {
            get {
                return ResourceManager.GetString("ListDetails_NoSelection_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listening on Port:.
        /// </summary>
        public static string Listening_on_Port_Text {
            get {
                return ResourceManager.GetString("Listening_on_Port_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local Test Avatar Detected.
        /// </summary>
        public static string LocalTestAvatar_Text {
            get {
                return ResourceManager.GetString("LocalTestAvatar_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local Test Avatars are not supported and will cause issues.
        /// </summary>
        public static string LocalTestAvatarTooltip_Content {
            get {
                return ResourceManager.GetString("LocalTestAvatarTooltip_Content", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Initializing modules....
        /// </summary>
        public static string Main_InitializingModules {
            get {
                return ResourceManager.GetString("Main_InitializingModules", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string Main_Loading {
            get {
                return ResourceManager.GetString("Main_Loading", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Modules.
        /// </summary>
        public static string Main_Modules_Header {
            get {
                return ResourceManager.GetString("Main_Modules_Header", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Not listening.
        /// </summary>
        public static string Main_Receive_Disconnected {
            get {
                return ResourceManager.GetString("Main_Receive_Disconnected", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Receive.
        /// </summary>
        public static string Main_Receive_Label {
            get {
                return ResourceManager.GetString("Main_Receive_Label", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to OSC received from VRChat on the local listening port.
        /// </summary>
        public static string Main_Receive_Tooltip {
            get {
                return ResourceManager.GetString("Main_Receive_Tooltip", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to VRCFaceTracking OSC relay.
        /// </summary>
        public static string Main_Relay_Tooltip {
            get {
                return ResourceManager.GetString("Main_Relay_Tooltip", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string Main_Send_Label {
            get {
                return ResourceManager.GetString("Main_Send_Label", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Main_Status_Header {
            get {
                return ResourceManager.GetString("Main_Status_Header", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Tracking module.
        /// </summary>
        public static string Main_TrackingModule_Label {
            get {
                return ResourceManager.GetString("Main_TrackingModule_Label", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Face tracking module input.
        /// </summary>
        public static string Main_TrackingModule_Tooltip {
            get {
                return ResourceManager.GetString("Main_TrackingModule_Tooltip", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to VRChat avatar.
        /// </summary>
        public static string Main_VRChat_Tooltip {
            get {
                return ResourceManager.GetString("Main_VRChat_Tooltip", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Module Page.
        /// </summary>
        public static string ModulePage_Text {
            get {
                return ResourceManager.GetString("ModulePage_Text", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Select an item from the list..
        /// </summary>
        public static string ModuleRegistry_NoSelection_Text {
            get {
                return ResourceManager.GetString("ModuleRegistry_NoSelection_Text", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to msgs/sec Incoming.
        /// </summary>
        public static string msIncoming_Text {
            get {
                return ResourceManager.GetString("msIncoming_Text", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to msgs/sec Outgoing.
        /// </summary>
        public static string msOutgoing_Text {
            get {
                return ResourceManager.GetString("msOutgoing_Text", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Adjust VRCFaceTracking Parameters..
        /// </summary>
        public static string Mutation_Adjust_VRCFaceTracking_Parameters {
            get {
                return ResourceManager.GetString("Mutation_Adjust_VRCFaceTracking_Parameters", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Beta.
        /// </summary>
        public static string Mutation_Beta {
            get {
                return ResourceManager.GetString("Mutation_Beta", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Calibration.
        /// </summary>
        public static string Mutation_Calibration {
            get {
                return ResourceManager.GetString("Mutation_Calibration", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Calibration Blend.
        /// </summary>
        public static string Mutation_Calibration_Blend {
            get {
                return ResourceManager.GetString("Mutation_Calibration_Blend", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cheek.
        /// </summary>
        public static string Mutation_Cheek {
            get {
                return ResourceManager.GetString("Mutation_Cheek", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cheek Squint.
        /// </summary>
        public static string Mutation_Cheek_Squint {
            get {
                return ResourceManager.GetString("Mutation_Cheek_Squint", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Continuous Calibration.
        /// </summary>
        public static string Mutation_Continuous_Calibration {
            get {
                return ResourceManager.GetString("Mutation_Continuous_Calibration", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Data Filter.
        /// </summary>
        public static string Mutation_Data_Filter {
            get {
                return ResourceManager.GetString("Mutation_Data_Filter", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to [DEBUG] Calibration Delta.
        /// </summary>
        public static string Mutation_DEBUG_Calibration_Delta {
            get {
                return ResourceManager.GetString("Mutation_DEBUG_Calibration_Delta", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to [DEBUG] Log Data.
        /// </summary>
        public static string Mutation_DEBUG_Log_Data {
            get {
                return ResourceManager.GetString("Mutation_DEBUG_Log_Data", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to [DEBUG] Step Delta.
        /// </summary>
        public static string Mutation_DEBUG_Step_Delta {
            get {
                return ResourceManager.GetString("Mutation_DEBUG_Step_Delta", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to [DEBUG] Window Size.
        /// </summary>
        public static string Mutation_DEBUG_Window_Size {
            get {
                return ResourceManager.GetString("Mutation_DEBUG_Window_Size", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Default data filtering for VRCFaceTracking expressions..
        /// </summary>
        public static string Mutation_Default_data_filtering_for_VRCFaceTracking_expressions {
            get {
                return ResourceManager.GetString("Mutation_Default_data_filtering_for_VRCFaceTracking_expressions", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Derivative Cutoff.
        /// </summary>
        public static string Mutation_Derivative_Cutoff {
            get {
                return ResourceManager.GetString("Mutation_Derivative_Cutoff", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Eye Squint.
        /// </summary>
        public static string Mutation_Eye_Squint {
            get {
                return ResourceManager.GetString("Mutation_Eye_Squint", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Eye Wide.
        /// </summary>
        public static string Mutation_Eye_Wide {
            get {
                return ResourceManager.GetString("Mutation_Eye_Wide", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Eyebrow Lowerer.
        /// </summary>
        public static string Mutation_Eyebrow_Lowerer {
            get {
                return ResourceManager.GetString("Mutation_Eyebrow_Lowerer", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Eyebrow Raiser.
        /// </summary>
        public static string Mutation_Eyebrow_Raiser {
            get {
                return ResourceManager.GetString("Mutation_Eyebrow_Raiser", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to EyeLid Blend.
        /// </summary>
        public static string Mutation_EyeLid_Blend {
            get {
                return ResourceManager.GetString("Mutation_EyeLid_Blend", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to EyeLook Symmetrize.
        /// </summary>
        public static string Mutation_EyeLook_Symmetrize {
            get {
                return ResourceManager.GetString("Mutation_EyeLook_Symmetrize", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Head Position (Forward-Back).
        /// </summary>
        public static string Mutation_Head_Position_Forward_Back {
            get {
                return ResourceManager.GetString("Mutation_Head_Position_Forward_Back", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Head Position (Side-to-Side).
        /// </summary>
        public static string Mutation_Head_Position_Side_to_Side {
            get {
                return ResourceManager.GetString("Mutation_Head_Position_Side_to_Side", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Head Position (Up-Down).
        /// </summary>
        public static string Mutation_Head_Position_Up_Down {
            get {
                return ResourceManager.GetString("Mutation_Head_Position_Up_Down", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Head Rotation (Side Tilt).
        /// </summary>
        public static string Mutation_Head_Rotation_Side_Tilt {
            get {
                return ResourceManager.GetString("Mutation_Head_Rotation_Side_Tilt", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Head Rotation (Side-to-Side).
        /// </summary>
        public static string Mutation_Head_Rotation_Side_to_Side {
            get {
                return ResourceManager.GetString("Mutation_Head_Rotation_Side_to_Side", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Head Rotation (Up-Down Tilt).
        /// </summary>
        public static string Mutation_Head_Rotation_Up_Down_Tilt {
            get {
                return ResourceManager.GetString("Mutation_Head_Rotation_Up_Down_Tilt", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Jaw.
        /// </summary>
        public static string Mutation_Jaw {
            get {
                return ResourceManager.GetString("Mutation_Jaw", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Jaw Forward / Backward.
        /// </summary>
        public static string Mutation_Jaw_Forward_Backward {
            get {
                return ResourceManager.GetString("Mutation_Jaw_Forward_Backward", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Jaw Sideways.
        /// </summary>
        public static string Mutation_Jaw_Sideways {
            get {
                return ResourceManager.GetString("Mutation_Jaw_Sideways", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Lip Funnel.
        /// </summary>
        public static string Mutation_Lip_Funnel {
            get {
                return ResourceManager.GetString("Mutation_Lip_Funnel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Lip Pucker.
        /// </summary>
        public static string Mutation_Lip_Pucker {
            get {
                return ResourceManager.GetString("Mutation_Lip_Pucker", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Lip Suck.
        /// </summary>
        public static string Mutation_Lip_Suck {
            get {
                return ResourceManager.GetString("Mutation_Lip_Suck", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to LipSuck Limiter.
        /// </summary>
        public static string Mutation_LipSuck_Limiter {
            get {
                return ResourceManager.GetString("Mutation_LipSuck_Limiter", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Minimum Cutoff.
        /// </summary>
        public static string Mutation_Minimum_Cutoff {
            get {
                return ResourceManager.GetString("Mutation_Minimum_Cutoff", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Mouth Frown.
        /// </summary>
        public static string Mutation_Mouth_Frown {
            get {
                return ResourceManager.GetString("Mutation_Mouth_Frown", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Mouth Open.
        /// </summary>
        public static string Mutation_Mouth_Open {
            get {
                return ResourceManager.GetString("Mutation_Mouth_Open", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Mouth Press.
        /// </summary>
        public static string Mutation_Mouth_Press {
            get {
                return ResourceManager.GetString("Mutation_Mouth_Press", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Mouth Raiser.
        /// </summary>
        public static string Mutation_Mouth_Raiser {
            get {
                return ResourceManager.GetString("Mutation_Mouth_Raiser", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Mouth Sideways.
        /// </summary>
        public static string Mutation_Mouth_Sideways {
            get {
                return ResourceManager.GetString("Mutation_Mouth_Sideways", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Mouth Smile.
        /// </summary>
        public static string Mutation_Mouth_Smile {
            get {
                return ResourceManager.GetString("Mutation_Mouth_Smile", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Mouth Stretch.
        /// </summary>
        public static string Mutation_Mouth_Stretch {
            get {
                return ResourceManager.GetString("Mutation_Mouth_Stretch", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Mouth Tightener.
        /// </summary>
        public static string Mutation_Mouth_Tightener {
            get {
                return ResourceManager.GetString("Mutation_Mouth_Tightener", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to MouthClosed.
        /// </summary>
        public static string Mutation_MouthClosed {
            get {
                return ResourceManager.GetString("Mutation_MouthClosed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to MouthClosed/JawOpen Clamp.
        /// </summary>
        public static string Mutation_MouthClosed_JawOpen_Clamp {
            get {
                return ResourceManager.GetString("Mutation_MouthClosed_JawOpen_Clamp", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Neck.
        /// </summary>
        public static string Mutation_Neck {
            get {
                return ResourceManager.GetString("Mutation_Neck", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Normalizes tracking data..
        /// </summary>
        public static string Mutation_Normalizes_tracking_data {
            get {
                return ResourceManager.GetString("Mutation_Normalizes_tracking_data", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Nose.
        /// </summary>
        public static string Mutation_Nose {
            get {
                return ResourceManager.GetString("Mutation_Nose", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Nose Sneer.
        /// </summary>
        public static string Mutation_Nose_Sneer {
            get {
                return ResourceManager.GetString("Mutation_Nose_Sneer", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Parameter Adjustment.
        /// </summary>
        public static string Mutation_Parameter_Adjustment {
            get {
                return ResourceManager.GetString("Mutation_Parameter_Adjustment", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Processes data to conform to Unified Expressions..
        /// </summary>
        public static string Mutation_Processes_data_to_conform_to_Unified_Expressions {
            get {
                return ResourceManager.GetString("Mutation_Processes_data_to_conform_to_Unified_Expressions", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Reset Calibration.
        /// </summary>
        public static string Mutation_Reset_Calibration {
            get {
                return ResourceManager.GetString("Mutation_Reset_Calibration", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Reset Values.
        /// </summary>
        public static string Mutation_Reset_Values {
            get {
                return ResourceManager.GetString("Mutation_Reset_Values", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Tongue Directions.
        /// </summary>
        public static string Mutation_Tongue_Directions {
            get {
                return ResourceManager.GetString("Mutation_Tongue_Directions", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Tongue Miscellaneous.
        /// </summary>
        public static string Mutation_Tongue_Miscellaneous {
            get {
                return ResourceManager.GetString("Mutation_Tongue_Miscellaneous", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Tongue Out.
        /// </summary>
        public static string Mutation_Tongue_Out {
            get {
                return ResourceManager.GetString("Mutation_Tongue_Out", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Unified Correctors.
        /// </summary>
        public static string Mutation_Unified_Correctors {
            get {
                return ResourceManager.GetString("Mutation_Unified_Correctors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install some from here!.
        /// </summary>
        public static string no_modules_installed_warning_ButtonText {
            get {
                return ResourceManager.GetString("no_modules_installed_warning_ButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You appear to have no modules installed..
        /// </summary>
        public static string no_modules_installed_warning_Description {
            get {
                return ResourceManager.GetString("no_modules_installed_warning_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Modules Installed.
        /// </summary>
        public static string no_modules_installed_warning_Title {
            get {
                return ResourceManager.GetString("no_modules_installed_warning_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Local Storage.
        /// </summary>
        public static string OpenLocalStorageCard_Header {
            get {
                return ResourceManager.GetString("OpenLocalStorageCard_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We noticed your OSC was turned off in VRChat, we&apos;ve just enabled it for you. If the game was open when this happened, you may need to manually enable it from your raidal menu. If not, you should be good to go!.
        /// </summary>
        public static string osc_was_disabled_warning_Description {
            get {
                return ResourceManager.GetString("osc_was_disabled_warning_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OSC Settings Modified.
        /// </summary>
        public static string osc_was_disabled_warning_Title {
            get {
                return ResourceManager.GetString("osc_was_disabled_warning_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Where should OSC Data be sent?.
        /// </summary>
        public static string OscSettings_Description {
            get {
                return ResourceManager.GetString("OscSettings_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OSC Address.
        /// </summary>
        public static string OscSettings_Header {
            get {
                return ResourceManager.GetString("OscSettings_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OSC Status.
        /// </summary>
        public static string OSCStatus_Text {
            get {
                return ResourceManager.GetString("OSCStatus_Text", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Copied to clipboard..
        /// </summary>
        public static string Output_Copied {
            get {
                return ResourceManager.GetString("Output_Copied", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Copy all to clipboard.
        /// </summary>
        public static string Output_CopyAll_Tooltip {
            get {
                return ResourceManager.GetString("Output_CopyAll_Tooltip", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Log saved..
        /// </summary>
        public static string Output_Saved {
            get {
                return ResourceManager.GetString("Output_Saved", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Save Log.
        /// </summary>
        public static string Output_SaveLog_Title {
            get {
                return ResourceManager.GetString("Output_SaveLog_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Save to file.
        /// </summary>
        public static string Output_SaveToFile_Tooltip {
            get {
                return ResourceManager.GetString("Output_SaveToFile_Tooltip", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Text files.
        /// </summary>
        public static string Output_TextFile_Type {
            get {
                return ResourceManager.GetString("Output_TextFile_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameters.
        /// </summary>
        public static string Parameters_Text {
            get {
                return ResourceManager.GetString("Parameters_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy Policy.
        /// </summary>
        public static string PrivacyPolicyCard_Header {
            get {
                return ResourceManager.GetString("PrivacyPolicyCard_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rating.
        /// </summary>
        public static string Rating_Text {
            get {
                return ResourceManager.GetString("Rating_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing module....
        /// </summary>
        public static string Registry_Applying {
            get {
                return ResourceManager.GetString("Registry_Applying", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Restart required.
        /// </summary>
        public static string Registry_AwaitingRestart {
            get {
                return ResourceManager.GetString("Registry_AwaitingRestart", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Connecting to the download server (up to 30 seconds)...
        /// </summary>
        public static string Registry_Connecting {
            get {
                return ResourceManager.GetString("Registry_Connecting", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Downloading module....
        /// </summary>
        public static string Registry_Downloading {
            get {
                return ResourceManager.GetString("Registry_Downloading", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Downloading module: {0:0.0} / {1:0.0} MB.
        /// </summary>
        public static string Registry_DownloadSizeKnown {
            get {
                return ResourceManager.GetString("Registry_DownloadSizeKnown", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Downloading module: {0:0.0} MB (total size unavailable).
        /// </summary>
        public static string Registry_DownloadSizeUnknown {
            get {
                return ResourceManager.GetString("Registry_DownloadSizeUnknown", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Extracting module....
        /// </summary>
        public static string Registry_Extracting {
            get {
                return ResourceManager.GetString("Registry_Extracting", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Installation failed: {0}.
        /// </summary>
        public static string Registry_Failure {
            get {
                return ResourceManager.GetString("Registry_Failure", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Download server returned HTTP {0}.
        /// </summary>
        public static string Registry_HttpError {
            get {
                return ResourceManager.GetString("Registry_HttpError", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Install.
        /// </summary>
        public static string Registry_Install {
            get {
                return ResourceManager.GetString("Registry_Install", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Installed.
        /// </summary>
        public static string Registry_Installed {
            get {
                return ResourceManager.GetString("Registry_Installed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Installed successfully..
        /// </summary>
        public static string Registry_Installed_Success {
            get {
                return ResourceManager.GetString("Registry_Installed_Success", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Installing....
        /// </summary>
        public static string Registry_Installing {
            get {
                return ResourceManager.GetString("Registry_Installing", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Install from .zip.
        /// </summary>
        public static string Registry_InstallZip_Tooltip {
            get {
                return ResourceManager.GetString("Registry_InstallZip_Tooltip", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Could not connect to the download server.
        /// </summary>
        public static string Registry_NetworkError {
            get {
                return ResourceManager.GetString("Registry_NetworkError", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Not installed.
        /// </summary>
        public static string Registry_NotInstalled {
            get {
                return ResourceManager.GetString("Registry_NotInstalled", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Update available.
        /// </summary>
        public static string Registry_Outdated {
            get {
                return ResourceManager.GetString("Registry_Outdated", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The module package could not be installed..
        /// </summary>
        public static string Registry_Package_Invalid {
            get {
                return ResourceManager.GetString("Registry_Package_Invalid", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Preparing download....
        /// </summary>
        public static string Registry_Preparing {
            get {
                return ResourceManager.GetString("Registry_Preparing", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Retry install.
        /// </summary>
        public static string Registry_Retry {
            get {
                return ResourceManager.GetString("Registry_Retry", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Search modules.
        /// </summary>
        public static string Registry_Search_Watermark {
            get {
                return ResourceManager.GetString("Registry_Search_Watermark", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Secure connection (SSL/TLS) failed.
        /// </summary>
        public static string Registry_SslError {
            get {
                return ResourceManager.GetString("Registry_SslError", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Download timed out. Check the network connection and retry..
        /// </summary>
        public static string Registry_Timeout {
            get {
                return ResourceManager.GetString("Registry_Timeout", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Uninstall.
        /// </summary>
        public static string Registry_Uninstall {
            get {
                return ResourceManager.GetString("Registry_Uninstall", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ZIP files.
        /// </summary>
        public static string Registry_ZipFiles_Type {
            get {
                return ResourceManager.GetString("Registry_ZipFiles_Type", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Re-Initialize.
        /// </summary>
        public static string ReInitButton_Content {
            get {
                return ResourceManager.GetString("ReInitButton_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset all VRChat OSC config data (will be regenerated when avatar is reloaded).
        /// </summary>
        public static string ResetAvatarConfButton_Description {
            get {
                return ResourceManager.GetString("ResetAvatarConfButton_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset VRChat Configs.
        /// </summary>
        public static string ResetAvatarConfButton_Header {
            get {
                return ResourceManager.GetString("ResetAvatarConfButton_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string ResetButton_Content {
            get {
                return ResourceManager.GetString("ResetButton_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset all data stored by VRCFT in your AppData folder.
        /// </summary>
        public static string ResetVRCFTButton_Description {
            get {
                return ResourceManager.GetString("ResetVRCFTButton_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset VRCFT.
        /// </summary>
        public static string ResetVRCFTButton_Header {
            get {
                return ResourceManager.GetString("ResetVRCFTButton_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danger, danger. High voltage...
        /// </summary>
        public static string RiskySettings_Description {
            get {
                return ResourceManager.GetString("RiskySettings_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Risky Settings.
        /// </summary>
        public static string RiskySettings_Header {
            get {
                return ResourceManager.GetString("RiskySettings_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending on Port:.
        /// </summary>
        public static string Sending_on_Port_Text {
            get {
                return ResourceManager.GetString("Sending_on_Port_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VRChat OSC App to allow AV3 Avatars to interact with eye and lip tracking runtimes.
        /// </summary>
        public static string Settings_About_Text {
            get {
                return ResourceManager.GetString("Settings_About_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VRChat OSC App to allow AV3 Avatars to interact with eye and lip tracking runtimes.
        /// </summary>
        public static string Settings_AboutDescription_Text {
            get {
                return ResourceManager.GetString("Settings_AboutDescription_Text", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ADVANCED.
        /// </summary>
        public static string Settings_AdvancedSection {
            get {
                return ResourceManager.GetString("Settings_AdvancedSection", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to commits.
        /// </summary>
        public static string Settings_Commits {
            get {
                return ResourceManager.GetString("Settings_Commits", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Contributors.
        /// </summary>
        public static string Settings_Contributors {
            get {
                return ResourceManager.GetString("Settings_Contributors", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Destination IP.
        /// </summary>
        public static string Settings_DestinationIp {
            get {
                return ResourceManager.GetString("Settings_DestinationIp", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Gremlin Mode.
        /// </summary>
        public static string Settings_GremlinMode {
            get {
                return ResourceManager.GetString("Settings_GremlinMode", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to OSC SETTINGS.
        /// </summary>
        public static string Settings_OscSection {
            get {
                return ResourceManager.GetString("Settings_OscSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personalization.
        /// </summary>
        public static string Settings_Personalization_Text {
            get {
                return ResourceManager.GetString("Settings_Personalization_Text", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Receive Port (Legacy).
        /// </summary>
        public static string Settings_ReceivePort {
            get {
                return ResourceManager.GetString("Settings_ReceivePort", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Send Port.
        /// </summary>
        public static string Settings_SendPort {
            get {
                return ResourceManager.GetString("Settings_SendPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        public static string Settings_Theme_Dark_Content {
            get {
                return ResourceManager.GetString("Settings_Theme_Dark_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        public static string Settings_Theme_Default_Content {
            get {
                return ResourceManager.GetString("Settings_Theme_Default_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        public static string Settings_Theme_Light_Content {
            get {
                return ResourceManager.GetString("Settings_Theme_Light_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        public static string Settings_Theme_Text {
            get {
                return ResourceManager.GetString("Settings_Theme_Text", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string Settings_UnknownVersion {
            get {
                return ResourceManager.GetString("Settings_UnknownVersion", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Version {0}.
        /// </summary>
        public static string Settings_Version {
            get {
                return ResourceManager.GetString("Settings_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy Statement.
        /// </summary>
        public static string SettingsPage_PrivacyTermsLink_Content {
            get {
                return ResourceManager.GetString("SettingsPage_PrivacyTermsLink_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://github.com/benaclejames/VRCFaceTracking.
        /// </summary>
        public static string SettingsPage_PrivacyTermsLink_NavigateUri {
            get {
                return ResourceManager.GetString("SettingsPage_PrivacyTermsLink_NavigateUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ListDetails.
        /// </summary>
        public static string Shell_ListDetails_Content {
            get {
                return ResourceManager.GetString("Shell_ListDetails_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Shell_Main_Content {
            get {
                return ResourceManager.GetString("Shell_Main_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module Registry.
        /// </summary>
        public static string Shell_ModuleRegistry_Content {
            get {
                return ResourceManager.GetString("Shell_ModuleRegistry_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output.
        /// </summary>
        public static string Shell_Output_Content {
            get {
                return ResourceManager.GetString("Shell_Output_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameters.
        /// </summary>
        public static string Shell_Parameters_Content {
            get {
                return ResourceManager.GetString("Shell_Parameters_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tracking Settings.
        /// </summary>
        public static string Shell_TrackingSettings_Content {
            get {
                return ResourceManager.GetString("Shell_TrackingSettings_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select which app theme to display.
        /// </summary>
        public static string ThemeSettings_Description {
            get {
                return ResourceManager.GetString("ThemeSettings_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App theme.
        /// </summary>
        public static string ThemeSettings_Header {
            get {
                return ResourceManager.GetString("ThemeSettings_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle Tracking.
        /// </summary>
        public static string ToggleTracking_Content {
            get {
                return ResourceManager.GetString("ToggleTracking_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heighten the influence your expressions make on calibration temporarily.
        /// </summary>
        public static string TrackingCalibrateButton_Description {
            get {
                return ResourceManager.GetString("TrackingCalibrateButton_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calibrate.
        /// </summary>
        public static string TrackingCalibrateButton_Header {
            get {
                return ResourceManager.GetString("TrackingCalibrateButton_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usage Instructions.
        /// </summary>
        public static string UsageInstructions_Text {
            get {
                return ResourceManager.GetString("UsageInstructions_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string Version_Text {
            get {
                return ResourceManager.GetString("Version_Text", resourceCulture);
            }
        }
    }
}
